name: Building songrec for amd64
run-name: ${{ github.actor }} is building songrec for amd64 debian
on:
  push:
    tags:
      - '*'
permissions:
  contents: write

jobs:
  build-for-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Preparing chroot
        id: preparing-chroot
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y mmdebstrap systemd-container debian-archive-keyring
          sudo mmdebstrap --include sudo,curl,build-essential,devscripts trixie /var/lib/machines/amd64-debian
          echo "Container successfully created"
      - name: Preparing repository
        uses: actions/checkout@v4
      - name: Building songrec
        id: building_songrec
        run: |
          cp -v ${{ github.workspace }}/prepare-build-chroot.sh /tmp/
          cp -v ${{ github.workspace }}/build-songrec.sh /tmp/
          sudo systemd-nspawn --bind /tmp:/tmp/hosttmp --bind-ro /etc/resolv.conf --hostname localhost --machine amd64-debian -- sh /tmp/hosttmp/prepare-build-chroot.sh
          sudo systemd-nspawn --bind /tmp:/tmp/hosttmp --bind-ro /etc/resolv.conf --hostname localhost --machine amd64-debian --user builder -- sh /tmp/hosttmp/build-songrec.sh
      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: /tmp/songrec_deb/
      - name: Creating release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /tmp/songrec_deb/*

